'use client';

import { useEffect } from 'react';

const T={
'Dashboard':'Bosh sahifa','Daily control':'Kunlik nazorat','Students':'O‘quvchilar','Groups':'Guruhlar','Teachers & Admin':'O‘qituvchilar va adminlar','Finance':'Moliya','Reports':'Hisobotlar','Gamification':'Gamifikatsiya','Shop':'Do‘kon','Leaderboard':'Reyting','Black list':'Qora ro‘yxat','Backup':'Zaxira','Restore':'Tiklash','Workspace':'Ish maydoni','English':'Ingliz tili','History':'Tarix','All courses':'Barcha kurslar','English workspace':'Ingliz tili bo‘limi','History workspace':'Tarix bo‘limi','All courses workspace':'Barcha kurslar',
'Active students':'Faol o‘quvchilar','Assigned staff':'Biriktirilgan xodimlar','Attendance':'Davomat','Homework':'Uy vazifasi','ARK Coins':'ARK Coin','This month':'Shu oy','current course':'joriy kurs','active groups':'faol guruhlar','assigned staff':'biriktirilgan xodimlar','marked lessons':'belgilangan darslar','submitted score':'topshirilgan natija','student balances':'o‘quvchilar balansi','collected payments':'yig‘ilgan to‘lovlar','COURSE STRUCTURE':'KURS TUZILMASI','Manage':'Boshqarish','TOP BALANCES':'ENG YUQORI BALANSLAR','View all':'Barchasini ko‘rish','No schedule':'Jadval yo‘q','Unassigned':'Biriktirilmagan','MANAGEMENT':'BOSHQARUV','Quick actions':'Tezkor amallar',
'Attendance, topic and homework':'Davomat, mavzu va uy vazifasi','Parents and monthly payments':'Oylik to‘lovlar','Coins, XP and rewards':'Coin, XP va sovg‘alar','Spend coins on rewards':'Coinlarni sovg‘alarga sarflash','DAILY CONTROL':'KUNLIK NAZORAT','Topic, homework, attendance and rewards in one place.':'Mavzu, uy vazifasi, davomat va mukofotlar bir joyda.','Done':'Bajarildi','Partial':'Qisman','Not done':'Bajarilmadi','Absent':'Kelmagan','Progress':'Natija','today':'bugun','LESSON SETUP':'DARS SOZLAMASI','Topic & homework':'Mavzu va uy vazifasi','Lesson topic':'Dars mavzusi','Homework 1':'Uy vazifasi 1','Homework 2':'Uy vazifasi 2','Homework 3':'Uy vazifasi 3','Homework 4':'Uy vazifasi 4','STUDENT CHECK':'O‘QUVCHI NAZORATI','Attendance & homework':'Davomat va uy vazifasi','Student':'O‘quvchi','Present':'Keldi','LIVE LESSONS':'HAFTALIK DARSLAR','Weekly counter':'Haftalik hisob','live lessons / week':'haftalik darslar',
'STUDENT DIRECTORY':'O‘QUVCHILAR RO‘YXATI','Search':'Qidirish','Add student':'O‘quvchi qo‘shish','Course / Group':'Kurs / Guruh','Parent':'Ota-ona','Parent phone':'Ota-ona telefoni','Phone':'Telefon','Coins / XP':'Coin / XP','No students match this course.':'Bu kursda mos o‘quvchi topilmadi.','STAFF DIRECTORY':'XODIMLAR RO‘YXATI','Staff':'Xodimlar','Teachers':'O‘qituvchilar','Admins':'Adminlar','active':'faol','teaching staff':'o‘qituvchilar','management':'boshqaruv','Add staff':'Xodim qo‘shish','No phone':'Telefon yo‘q','Add teachers and admins to manage courses.':'Kurslarni boshqarish uchun o‘qituvchi va admin qo‘shing.',
'FINANCE':'MOLIYA','Every month is stored separately for each student.':'Har bir o‘quvchining oylik to‘lovi alohida saqlanadi.','Monthly fee':'Oylik to‘lov','Total':'Jami','finance records':'moliya yozuvlari','visible students':'ko‘rinayotgan o‘quvchilar','ARK REWARD ECONOMY':'ARK MUKOFOT TIZIMI','Coins + XP':'Coin + XP','Coins can be spent in the shop. XP never decreases and controls the student level.':'Coinlarni do‘konda sarflash mumkin. XP kamaymaydi va darajani belgilaydi.','Reason':'Sabab','Give coins':'Coin berish','LEVELS':'DARAJALAR','Student progress':'O‘quvchi rivoji','RECENT ACTIVITY':'SO‘NGGI FAOLLIK','Coin transactions':'Coin operatsiyalari','New coin transactions will appear here.':'Yangi coin operatsiyalari shu yerda chiqadi.',
'ARK SHOP':'ARK DO‘KON','Rewards marketplace':'Sovg‘alar do‘koni','Students spend ARK Coins; XP stays untouched.':'O‘quvchilar ARK Coin sarflaydi; XP kamaymaydi.','New reward':'Yangi sovg‘a','Coins':'Coin','Stock':'Ombor','Add item':'Sovg‘a qo‘shish','Buy for student':'O‘quvchi uchun xarid','Purchase':'Xarid qilish','ORDERS':'BUYURTMALAR','Shop requests':'Do‘kon buyurtmalari','Pending':'Kutilmoqda','Completed':'Bajarildi','Cancelled':'Bekor qilindi','No shop orders yet.':'Hozircha buyurtma yo‘q.','TOP STUDENTS':'ENG YAXSHI O‘QUVCHILAR','RANKING':'REYTING',
'CURRENT MONTH':'JORIY OY','STUDENT FLOW':'O‘QUVCHILAR HARAKATI','Student status':'O‘quvchilar holati','All key counts are shown together.':'Barcha asosiy ko‘rsatkichlar bir joyda.','Finance overview':'Moliya ko‘rinishi','Expected':'Kutilgan','Collected':'To‘langan','Outstanding':'Qarzdorlik','DAILY GROUP REPORT':'KUNLIK GURUH HISOBOTI','Group comparison':'Guruhlar taqqoslanishi','Attendance and homework are calculated from Daily Control.':'Davomat va uy vazifasi Kunlik nazoratdan hisoblanadi.','Trial students':'Sinovdagi o‘quvchilar','Debtors':'Qarzdorlar','Paid this month':'Shu oy to‘laganlar','Left active group':'Faol guruhdan ketganlar','Left after trial':'Sinovdan keyin ketganlar','currently studying':'hozir o‘qimoqda','active structure':'faol tuzilma','payment due':'to‘lov muddati o‘tgan','trial period':'sinov muddati','students with payment':'to‘lov qilgan o‘quvchilar','left after activation':'faol bo‘lgandan keyin ketgan','did not continue':'davom ettirmagan','Expected, received and outstanding tuition.':'Kutilgan, to‘langan va qolgan oylik to‘lovlar.','No groups in this course yet.':'Bu kursda hali guruh yo‘q.',
'STUDENT LIFECYCLE':'O‘QUVCHI HOLATI','Status & billing control':'Holat va to‘lov nazorati','Active':'Faol','Trial':'Sinov','All statuses':'Barcha holatlar','Payment status':'To‘lov holati','Due day':'To‘lov kuni','Trial start':'Sinov boshlangan sana','Trial until':'Sinov tugash sanasi','Paid':'To‘langan','Overdue':'Kechikkan','No fee':'To‘lov belgilanmagan','Save':'Saqlash','Saved':'Saqlandi','Refresh':'Yangilash','Save changes':'O‘zgarishlarni saqlash','Saving…':'Saqlanmoqda…','Loading workspace…':'Bo‘lim yuklanmoqda…',
'Accountant workspace':'Buxgalter bo‘limi','ARK FINANCE':'ARK MOLIYA','Collected this month':'Shu oy yig‘ildi','Outstanding debt':'Jami qarz','Overdue students':'Qarzdor o‘quvchilar','PAYMENT REGISTER':'TO‘LOVLAR RO‘YXATI','Set monthly fee, due date and the month payments start. Unpaid amounts automatically appear as debt.':'Oylik summa, to‘lov kuni va boshlanish oyini belgilang. To‘lanmagan summa avtomatik qarzga tushadi.','Start month':'Boshlanish oyi','Debt':'Qarz','Shop manager':'Do‘kon boshqaruvchisi','NEW PRODUCT':'YANGI MAHSULOT','Add reward':'Sovg‘a qo‘shish','Name':'Nomi','Coin price':'Coin narxi','Product image':'Mahsulot rasmi','Uploading…':'Yuklanmoqda…','Add product':'Mahsulot qo‘shish','Image':'Rasm','Student requests':'O‘quvchi buyurtmalari','No orders yet':'Hozircha buyurtma yo‘q','Opening ARK Shop…':'ARK do‘kon ochilmoqda…',
'Profile link required':'Profilni bog‘lash kerak','Your account is active, but the admin still needs to connect it to your student profile.':'Hisobingiz faol, lekin admin uni o‘quvchi profilingizga bog‘lashi kerak.','ARK STUDENT':'ARK O‘QUVCHI','Spend your coins':'Coinlaringizni sarflang','Level':'Daraja','Home':'Bosh sahifa','Results':'Natijalar','Wallet':'Hamyon','Profile':'Profil','Sign in':'Kirish','Register':'Ro‘yxatdan o‘tish','SECURE ACCESS':'XAVFSIZ KIRISH','Welcome back':'Xush kelibsiz','Use your ARK Tracker account.':'ARK Tracker hisobingiz bilan kiring.','Email':'Email','Password':'Parol','Email not confirmed':'Email tasdiqlanmagan','Create account':'Hisob yaratish','Full name':'Ism-familiya','Role':'Rol','Request access':'Kirish so‘rovi','Access requests':'Kirish so‘rovlari','Owner':'Egasi','Admin':'Admin','Teacher':'O‘qituvchi','Accountant':'Buxgalter','Approve':'Tasdiqlash','Reject':'Rad etish','Suspend':'To‘xtatish','Activate':'Faollashtirish','Logout':'Chiqish','Sign out':'Chiqish',
'Mon':'Du','Tue':'Se','Wed':'Ch','Thu':'Pa','Fri':'Ju','Sat':'Sha','Sun':'Yak','Jan':'Yan','Feb':'Fev','Mar':'Mar','Apr':'Apr','May':'May','Jun':'Iyun','Jul':'Iyul','Aug':'Avg','Sep':'Sen','Oct':'Okt','Nov':'Noy','Dec':'Dek'
};
const P={'Search student':'O‘quvchi qidirish','Search':'Qidirish','Parent name':'Ota-ona ismi','Name':'Ism','Reason':'Sabab','New reward':'Yangi sovg‘a','Write task':'Vazifani yozing','e.g. Mathematics':'masalan: Matematika'};

function dynamic(s){let m;if((m=s.match(/^(\d+) active students$/i)))return `${m[1]} faol o‘quvchi`;if((m=s.match(/^(\d+) students$/i)))return `${m[1]} o‘quvchi`;if((m=s.match(/^(\d+) students · (.+)$/i)))return `${m[1]} o‘quvchi · ${m[2]}`;if((m=s.match(/^(\d+) in stock$/i)))return `Omborda: ${m[1]}`;if((m=s.match(/^(\d+) lessons\/wk$/i)))return `Haftasiga ${m[1]} dars`;if((m=s.match(/^(\d+) pending$/i)))return `${m[1]} kutilmoqda`;if((m=s.match(/^(\d+) rewards$/i)))return `${m[1]} sovg‘a`;if((m=s.match(/^Welcome, (.+)$/i)))return `Xush kelibsiz, ${m[1]}`;if((m=s.match(/^(.+) · monthly payments and debt control$/i)))return `${m[1]} · oylik to‘lov va qarz nazorati`;if((m=s.match(/^(.+) · products, coin prices, stock and orders$/i)))return `${m[1]} · mahsulotlar, coin narxi, ombor va buyurtmalar`;if((m=s.match(/^(.+) · rewards marketplace$/i)))return `${m[1]} · sovg‘alar do‘koni`;return s}
function tr(s){return T[s]||dynamic(s)}
function walk(root){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){const p=n.parentElement;if(!p||['SCRIPT','STYLE','TEXTAREA','CODE','PRE'].includes(p.tagName))continue;const raw=n.nodeValue,clean=raw.trim();if(!clean)continue;const next=tr(clean);if(next!==clean){const a=raw.match(/^\s*/)?.[0]||'',b=raw.match(/\s*$/)?.[0]||'';n.nodeValue=a+next+b}}root.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(el=>['placeholder','title','aria-label'].forEach(k=>{const v=el.getAttribute(k);if(!v)return;const next=P[v]||tr(v);if(next!==v)el.setAttribute(k,next)}))}
function pageClass(){const shell=document.querySelector('.app-shell');if(!shell)return;const active=shell.querySelector('.sidebar nav button.active');const s=(active?.textContent||'').trim().toLowerCase();const pairs=[[['students','o‘quvchilar'], 'students'],[['shop','do‘kon'],'shop'],[['dashboard','bosh sahifa'],'dashboard'],[['finance','moliya'],'finance'],[['reports','hisobotlar'],'reports'],[['daily control','kunlik nazorat'],'daily'],[['groups','guruhlar'],'groups'],[['teachers & admin','o‘qituvchilar va adminlar'],'staff'],[['gamification','gamifikatsiya'],'gamification'],[['leaderboard','reyting'],'leaderboard'],[['black list','qora ro‘yxat'],'blacklist']];let wanted='';for(const [names,key] of pairs)if(names.some(x=>s.includes(x))){wanted=`uz-page-${key}`;break}const old=[...shell.classList].filter(x=>x.startsWith('uz-page-'));if(old.length===1&&old[0]===wanted)return;old.forEach(x=>shell.classList.remove(x));if(wanted)shell.classList.add(wanted)}
export default function UzbekUI(){useEffect(()=>{document.documentElement.lang='uz';let raf=0;const run=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{walk(document.body);pageClass()})};run();const o=new MutationObserver(run);o.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});document.addEventListener('click',run,true);return()=>{o.disconnect();document.removeEventListener('click',run,true);cancelAnimationFrame(raf)}},[]);return null}
