'use client';
import {useState} from 'react';
import {Clock,CheckCircle2,UserX,LogOut,FileDown,Pencil,X,StopCircle,Play,Search} from 'lucide-react';
import {dailyCounts,formatTashkent,durationMinutes,durationLabel,statusLabel} from '@/lib/domain';
import type {AdminData,Attendance,Session} from '@/lib/types';
type Act=(action:string,params?:Record<string,unknown>)=>Promise<unknown>;
const localInput=(value:string|null)=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tashkent',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)).replace(' ','T'):'';
export function LivePanel({data,act,busy,selectedDate,sessionId,setSessionId,exportReport}:{data:AdminData;act:Act;busy:boolean;selectedDate:string;sessionId:string;setSessionId:(v:string)=>void;exportReport:(sessionId:string,preview?:boolean)=>Promise<void>}){
 const [search,setSearch]=useState(''),[editing,setEditing]=useState<Attendance|null>(null),[inTime,setInTime]=useState(''),[outTime,setOutTime]=useState(''),[note,setNote]=useState('');
 const sessions=data.sessions.filter(s=>s.lesson_date===selectedDate);
 const session=sessions.find(s=>s.id===sessionId)||sessions[0];
 const group=data.groups.find(g=>g.id===session?.group_id);
 const records=data.attendance.filter(a=>a.session_id===session?.id);
 const stats=dailyCounts(records,group?.late_grace_min??5);
 const rows=[...records].sort((a,b)=>(data.students.find(s=>s.id===a.student_id)?.name||'').localeCompare(data.students.find(s=>s.id===b.student_id)?.name||'','uz')).filter(r=>data.students.find(s=>s.id===r.student_id)?.name.toLowerCase().includes(search.toLowerCase()));
 const showEdit=(r:Attendance)=>{setEditing(r);setInTime(localInput(r.checked_in));setOutTime(localInput(r.checked_out));setNote(r.note||'');};
 async function editField(operation:'in'|'out'|'note'|'absent'|'clear',at?:string){
  if(!editing||!session)return;
  if(at&&!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(at)){alert('Sana va vaqtni to‘g‘ri kiriting');return;}
  await act('manual',{sessionId:session.id,studentId:editing.student_id,operation,at:at?new Date(at+':00+05:00').toISOString():null,note});
  setEditing(null);
 }
 return <section className="panel-block"><div className="section-heading"><div><span className="eyebrow">JONLI DAVOMAT</span><h2>{session?group?.name+' — Davomat sessiyasi':'Bugungi davomat'}</h2><p>{session?'O‘zgarishlar avtomatik yangilanadi.':'Bugungi darslardan birini admin panelda oching.'}</p></div><div className="toolbar-right">{session&&<button className="btn btn-outline" onClick={()=>exportReport(session.id,true)}><FileDown size={17}/> PDF hisobot</button>}</div></div>
 {!!sessions.length&&<div className="session-tabs">{sessions.map(s=><button className={'session-tab '+(s.id===session?.id?'active':'')} key={s.id} onClick={()=>setSessionId(s.id)}>{data.groups.find(g=>g.id===s.group_id)?.name||'Guruh'} <span className={'dot '+(s.status==='active'?'green':'grey')}/></button>)}</div>}
 {!session?<div className="empty-state big"><Clock size={36}/><h3>Hozircha dars ochilmagan</h3><p>Bosh sahifadan guruh darsini ochishingiz mumkin.</p></div>:
 <><div className="session-details"><div><span>Guruh</span><b>{group?.name}</b></div><div><span>O‘qituvchi</span><b>{group?.teacher||'Belgilanmagan'}</b></div><div><span>Dars vaqti</span><b>{formatTashkent(session.planned_start)} — {formatTashkent(session.planned_end)}</b></div><div><span>Holat</span><span className={'badge '+(session.status==='active'?'badge-green':'badge-grey')}>{session.status==='active'?'Davom etmoqda':'Yakunlangan'}</span></div></div>
 <div className="stat-grid five"><div className="stat-card"><span>Jami</span><strong>{stats.total}</strong></div><div className="stat-card good"><span>Kelganlar</span><strong>{stats.present}</strong></div><div className="stat-card danger"><span>Kelmaganlar</span><strong>{stats.absent}</strong></div><div className="stat-card warn"><span>Kechikkanlar</span><strong>{stats.late}</strong></div><div className="stat-card"><span>Ketishni belgilamagan</span><strong>{session.status==='closed'?stats.missingCheckout:'—'}</strong></div></div>
 <div className="table-panel"><div className="table-toolbar"><h3>O‘quvchilar ro‘yxati <span className="muted">({rows.length})</span></h3><div className="search-field"><Search size={17}/><input placeholder="Ism bo‘yicha qidirish" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-scroll"><table><thead><tr><th>O‘quvchi</th><th>Kelish</th><th>Ketish</th><th>Davomiylik</th><th>Holat</th><th>Izoh</th><th>Amallar</th></tr></thead><tbody>{rows.map(r=>{const st=data.students.find(s=>s.id===r.student_id),label=statusLabel(r,session.status==='closed',group?.late_grace_min??5);return <tr key={r.student_id}><td><span className="avatar mini">{st?.name.slice(0,1)||'?'}</span><b>{st?.name||'O‘quvchi'}</b></td><td className="mono">{formatTashkent(r.checked_in)}</td><td className="mono">{formatTashkent(r.checked_out)}</td><td>{durationLabel(durationMinutes(r.checked_in,r.checked_out))}</td><td><span className={'badge '+(!r.checked_in?(session.status==='closed'?'badge-red':'badge-grey'):r.late_min>(group?.late_grace_min??5)?'badge-gold':r.checked_out?'badge-blue':'badge-green')}>{label}</span></td><td>{r.note||'—'}</td><td className="row-actions">{!r.checked_in?<button className="btn btn-outline btn-small" disabled={busy} onClick={()=>act('manual',{sessionId:session.id,studentId:r.student_id,operation:'in'})}><CheckCircle2 size={14}/> Keldi</button>:!r.checked_out?<button className="btn btn-outline btn-small" disabled={busy} onClick={()=>act('manual',{sessionId:session.id,studentId:r.student_id,operation:'out'})}><LogOut size={14}/> Ketdi</button>:null}<button className="btn btn-outline btn-small" onClick={()=>showEdit(r)}><Pencil size={14}/> Tahrirlash</button></td></tr>})}</tbody></table></div>{!rows.length&&<div className="empty-state">Ushbu darsga o‘quvchilar qo‘shilmagan.</div>}</div>
 <div className="session-end">{session.status==='active'?<button className="btn btn-primary" disabled={busy} onClick={()=>{if(confirm(group?.name+' darsini yakunlaysizmi? Kelmaganlar avtomatik belgilanadi.'))act('end',{sessionId:session.id});}}><StopCircle size={18}/> DARSNI YAKUNLASH</button>:<span className="badge badge-grey">Dars yakunlangan · Hisobot tayyor</span>}<button className="btn btn-outline" onClick={()=>exportReport(session.id)}><FileDown size={17}/> PDF yuklab olish</button></div>
 </>}
 {editing&&<div className="modal-backdrop" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="form-head"><h3>Davomatni tahrirlash</h3><button className="icon-btn" onClick={()=>setEditing(null)}><X size={20}/></button></div><p>{data.students.find(s=>s.id===editing.student_id)?.name}</p><label>Kelish vaqti<input type="datetime-local" value={inTime} onChange={e=>setInTime(e.target.value)}/></label><button className="btn btn-outline btn-block" disabled={!inTime||busy} onClick={()=>editField('in',inTime)}>Kelish vaqtini saqlash</button><label>Ketish vaqti<input type="datetime-local" value={outTime} onChange={e=>setOutTime(e.target.value)}/></label><button className="btn btn-outline btn-block" disabled={!outTime||busy} onClick={()=>editField('out',outTime)}>Ketish vaqtini saqlash</button><label>Izoh<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><button className="btn btn-primary btn-block" disabled={busy} onClick={()=>editField('note')}>Izohni saqlash</button><div className="form-actions"><button className="btn btn-danger-light" disabled={busy} onClick={()=>{if(confirm('Kelmadi deb belgilaysizmi?'))editField('absent');}}><UserX size={16}/> Kelmadi</button><button className="btn btn-outline" disabled={busy} onClick={()=>editField('clear')}>Davomatni tozalash</button></div></div></div>}
 </section>;
}
