'use client';
import {useState} from 'react';
import {FileDown,Eye,Printer,CalendarDays,Download} from 'lucide-react';
import {dailyCounts} from '@/lib/domain';
import type {AdminData} from '@/lib/types';
export function ReportsPanel({data,date,setDate,onPdf,previewUrl,busy}:{data:AdminData;date:string;setDate:(s:string)=>void;onPdf:(mode:'preview'|'download'|'print',date:string,groupId:string)=>Promise<void>;previewUrl:string;busy:boolean}){
 const [groupId,setGroupId]=useState('');
 const sessions=data.sessions.filter(s=>s.lesson_date===date&&(!groupId||s.group_id===groupId));
 const records=data.attendance.filter(a=>sessions.some(s=>s.id===a.session_id));
 const present=records.filter(a=>a.checked_in).length,absent=records.filter(a=>a.status==='absent'&&!a.checked_in).length,late=records.filter(a=>a.checked_in&&a.late_min>(data.groups.find(g=>g.id===data.sessions.find(s=>s.id===a.session_id)?.group_id)?.late_grace_min??5)).length;
 const missing=records.filter(a=>a.checked_in&&!a.checked_out&&data.sessions.find(s=>s.id===a.session_id)?.status==='closed').length;
 return <section className="panel-block"><div className="section-heading"><div><span className="eyebrow">REPORTING</span><h2>Bugungi va tarixiy hisobotlar</h2><p>Sana yoki guruhni tanlab, rasmiy A4 hisobotni oling.</p></div></div>
 <div className="report-controls"><label>Sana<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Guruh<select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">Barcha guruhlar</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label></div>
 <div className="stat-grid four"><div className="stat-card good"><span>Kelganlar</span><strong>{present}</strong></div><div className="stat-card danger"><span>Kelmaganlar</span><strong>{absent}</strong></div><div className="stat-card warn"><span>Kechikkanlar</span><strong>{late}</strong></div><div className="stat-card"><span>Ketishni unutganlar</span><strong>{missing}</strong></div></div>
 <div className="report-grid"><div className="report-preview"><div className="card-title"><FileDown size={19}/><h3>PDF ko‘rinishi</h3></div>{previewUrl?<iframe title="Davomat hisobotining PDF ko‘rinishi" src={previewUrl} className="pdf-frame"/>:<div className="pdf-empty"><FileDown size={46}/><h3>Hisobot ko‘rinishini oching</h3><p>PDFni ko‘rish tugmasini bosing. Hisobot haqiqiy bazadagi ma’lumotlardan tuziladi.</p></div>}</div><aside className="report-aside"><div className="side-panel"><div className="card-title"><Download size={19}/><h3>Hisobotni olish</h3></div><button className="btn btn-primary btn-block" disabled={!sessions.length||busy} onClick={()=>onPdf('download',date,groupId)}><FileDown size={18}/> PDF yuklab olish</button><button className="btn btn-outline btn-block" disabled={!sessions.length||busy} onClick={()=>onPdf('preview',date,groupId)}><Eye size={18}/> PDF ko‘rinishi</button><button className="btn btn-outline btn-block" disabled={!sessions.length||busy} onClick={()=>onPdf('print',date,groupId)}><Printer size={18}/> Chop etish</button></div><div className="side-panel"><div className="card-title"><CalendarDays size={19}/><h3>Tanlangan darslar</h3></div>{sessions.length?sessions.map(s=><div className="side-row" key={s.id}><b>{data.groups.find(g=>g.id===s.group_id)?.name}</b><span className={'badge '+(s.status==='closed'?'badge-grey':'badge-green')}>{s.status==='closed'?'Yakunlangan':'Faol'}</span></div>):<p className="muted">Tanlangan sanada dars yo‘q.</p>}</div><div className="side-panel"><h3>Davomat ulushi</h3><div className="big-percent">{records.length?Math.round(present*100/records.length):0}%</div><div className="bar-track"><i style={{width:(records.length?Math.round(present*100/records.length):0)+'%'}}/></div><p className="muted">Kechikkanlar kelganlarga qo‘shib hisoblanadi.</p></div></aside></div>
 </section>;
}
