'use client';
import {useState} from 'react';
import {Plus,Pencil,Archive,RotateCcw,Users,UserPlus,Search,X} from 'lucide-react';
import type {AdminData,Group,Student} from '@/lib/types';
type Act=(action:string,params?:Record<string,unknown>)=>Promise<unknown>;
const weekdays=[['Du',1],['Se',2],['Cho',3],['Pa',4],['Ju',5],['Sha',6],['Ya',0]] as const;
export function GroupsPanel({data,act,busy}:{data:AdminData;act:Act;busy:boolean}){
 const [editing,setEditing]=useState<Group|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(''),[teacher,setTeacher]=useState(''),[start,setStart]=useState('09:00'),[end,setEnd]=useState('10:30'),[grace,setGrace]=useState(5),[days,setDays]=useState<number[]>([1,3,5]),[archived,setArchived]=useState(false);
 function edit(g?:Group){setEditing(g||null);setName(g?.name||'');setTeacher(g?.teacher||'');setStart(g?.starts_at?.slice(0,5)||'09:00');setEnd(g?.ends_at?.slice(0,5)||'10:30');setGrace(g?.late_grace_min??5);setDays(g?.weekdays||[1,3,5]);setOpen(true);}
 async function save(){const params={name,teacher,starts_at:start,ends_at:end,late_grace_min:grace,weekdays:days};await act(editing?'editGroup':'addGroup',editing?{id:editing.id,...params}:params);setOpen(false);}
 return <section className="panel-block"><div className="section-heading"><div><span className="eyebrow">GURUHLAR</span><h2>Guruhlarni boshqarish</h2><p>Dars vaqti, o‘qituvchi va kechikish chegarasini sozlang.</p></div><button className="btn btn-primary" onClick={()=>edit()}><Plus size={17}/> Guruh qo‘shish</button></div>
 {open&&<div className="form-panel"><div className="form-head"><h3>{editing?'Guruhni tahrirlash':'Yangi guruh'}</h3><button className="icon-btn" onClick={()=>setOpen(false)}><X size={20}/></button></div><div className="form-grid"><label>Guruh nomi<input value={name} onChange={e=>setName(e.target.value)} placeholder="IELTS"/></label><label>O‘qituvchi<input value={teacher} onChange={e=>setTeacher(e.target.value)} placeholder="O‘qituvchi ismi"/></label><label>Dars boshlanishi<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Dars tugashi<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Kechikish chegarasi (daqiqa)<input type="number" min={0} max={120} value={grace} onChange={e=>setGrace(Number(e.target.value))}/></label></div><p className="form-label">Dars kunlari</p><div className="weekday-row">{weekdays.map(([label,day])=><button key={day} className={'day-chip '+(days.includes(day)?'active':'')} onClick={()=>setDays(old=>old.includes(day)?old.filter(x=>x!==day):[...old,day])}>{label}</button>)}</div><div className="form-actions"><button className="btn btn-outline" onClick={()=>setOpen(false)}>Bekor qilish</button><button className="btn btn-primary" disabled={busy||!name.trim()} onClick={save}>Saqlash</button></div></div>}
 <div className="grid-groups">{data.groups.filter(g=>!g.archived).map(g=>{const size=data.memberships.filter(m=>m.group_id===g.id&&m.active&&!data.students.find(st=>st.id===m.student_id)?.archived).length;return <div className="entity-card" key={g.id}><div className="entity-icon"><Users size={23}/></div><h3>{g.name}</h3><p>{g.teacher||'O‘qituvchi belgilanmagan'}</p><div className="entity-info"><span>{g.starts_at.slice(0,5)} – {g.ends_at.slice(0,5)}</span><span>{size} nafar</span></div><p className="weekday-detail">{weekdays.filter(([,d])=>g.weekdays.includes(d)).map(([l])=>l).join(' · ')} · {g.late_grace_min} daqiqa</p><div className="card-actions"><button className="btn btn-outline" onClick={()=>edit(g)}><Pencil size={15}/> Tahrirlash</button><button className="btn btn-danger-light" disabled={busy} onClick={()=>{if(confirm(g.name+' guruhini arxivlashni tasdiqlaysizmi?'))act('editGroup',{id:g.id,archived:true});}}><Archive size={15}/> Arxiv</button></div></div>;})}</div>
 {!!data.groups.find(g=>g.archived)&&<div className="archived-list"><h3>Arxivdagi guruhlar</h3>{data.groups.filter(g=>g.archived).map(g=><div className="archive-row" key={g.id}>{g.name}<button className="btn btn-outline" disabled={busy} onClick={()=>act('editGroup',{id:g.id,archived:false})}><RotateCcw size={14}/> Tiklash</button></div>)}</div>}
 </section>;
}
export function StudentsPanel({data,act,busy}:{data:AdminData;act:Act;busy:boolean}){
 const [q,setQ]=useState(''),[editing,setEditing]=useState<Student|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(''),[groupIds,setGroupIds]=useState<string[]>([]),[showArchived,setShowArchived]=useState(false);
 function edit(st?:Student){setEditing(st||null);setName(st?.name||'');setGroupIds(st?data.memberships.filter(m=>m.student_id===st.id&&m.active).map(m=>m.group_id):[]);setOpen(true);}
 async function save(){const p={name,groupIds};await act(editing?'editStudent':'addStudent',editing?{id:editing.id,...p}:p);setOpen(false);}
 const groups=data.groups.filter(g=>!g.archived);
 const list=data.students.filter(st=>(showArchived||!st.archived)&&st.name.toLowerCase().includes(q.toLowerCase()));
 return <section className="panel-block"><div className="section-heading"><div><span className="eyebrow">O‘QUVCHILAR</span><h2>O‘quvchilar ro‘yxati</h2><p>Bir o‘quvchini bir nechta guruhga biriktirish mumkin.</p></div><button className="btn btn-primary" onClick={()=>edit()}><UserPlus size={17}/> O‘quvchi qo‘shish</button></div>
 {open&&<div className="form-panel"><div className="form-head"><h3>{editing?'O‘quvchini tahrirlash':'Yangi o‘quvchi'}</h3><button className="icon-btn" onClick={()=>setOpen(false)}><X size={20}/></button></div><label>Ism-familiya<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ism va familiya"/></label><p className="form-label">Guruhlarni belgilang</p><div className="group-checks">{groups.map(g=><label className="check-card" key={g.id}><input type="checkbox" checked={groupIds.includes(g.id)} onChange={e=>setGroupIds(v=>e.target.checked?[...v,g.id]:v.filter(id=>id!==g.id))}/>{g.name}</label>)}</div><div className="form-actions"><button className="btn btn-outline" onClick={()=>setOpen(false)}>Bekor qilish</button><button className="btn btn-primary" disabled={busy||name.trim().length<2||!groupIds.length} onClick={save}>Saqlash</button></div></div>}
 <div className="table-panel"><div className="table-toolbar"><div className="search-field"><Search size={18}/><input value={q} placeholder="O‘quvchini qidirish..." onChange={e=>setQ(e.target.value)}/></div><label className="toggle-archive"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Arxivdagilarni ko‘rsatish</label><span className="muted">{list.length} nafar</span></div><div className="table-scroll"><table><thead><tr><th>O‘quvchi</th><th>Guruhlar</th><th>Holati</th><th>Amallar</th></tr></thead><tbody>{list.map(st=><tr key={st.id}><td><span className="avatar mini">{st.name.slice(0,1)}</span><b>{st.name}</b></td><td>{data.memberships.filter(m=>m.student_id===st.id&&m.active).map(m=>data.groups.find(g=>g.id===m.group_id)?.name).filter(Boolean).join(', ')||'—'}</td><td><span className={'badge '+(st.archived?'badge-grey':'badge-green')}>{st.archived?'Arxivda':'Faol'}</span></td><td className="row-actions"><button className="btn btn-outline btn-small" onClick={()=>edit(st)}><Pencil size={14}/> Tahrirlash</button><button className="btn btn-danger-light btn-small" disabled={busy} onClick={()=>{if(confirm(st.name+' uchun arxiv holatini o‘zgartirasizmi?'))act('editStudent',{id:st.id,archived:!st.archived});}}>{st.archived?'Tiklash':'Arxivlash'}</button></td></tr>)}</tbody></table></div>{!list.length&&<div className="empty-state">Bu ro‘yxatda o‘quvchi topilmadi.</div>}</div></section>;
}
