'use client';
import {useState} from 'react';
import {Smartphone,ShieldCheck,Copy,CheckCircle2,Power,Plus} from 'lucide-react';
import type {AdminData} from '@/lib/types';
type Act=(action:string,params?:Record<string,unknown>)=>Promise<unknown>;
export function SettingsPanel({data,act,busy}:{data:AdminData;act:Act;busy:boolean}){
 const [label,setLabel]=useState('Samsung Note 10'),[generated,setGenerated]=useState<{token:string;label:string}|null>(null),[copied,setCopied]=useState(false);
 async function issue(){const r=await act('device',{label}) as {token:string;label:string};if(r?.token){setGenerated(r);setCopied(false);}}
 return <section className="panel-block"><div className="section-heading"><div><span className="eyebrow">SOZLAMALAR</span><h2>Davomat terminali</h2><p>Samsung Note 10 uchun cheklangan huquqli qurilma kodini yarating.</p></div></div><div className="settings-grid"><div className="side-panel"><div className="card-title"><Smartphone size={21}/><h3>Yangi terminal qo‘shish</h3></div><p className="muted">Telefon o‘quvchilar uchun faqat KELDIM va KETDIM amallarini bajaradi. Admin panelga kira olmaydi.</p><label>Qurilma nomi<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Samsung Note 10"/></label><button className="btn btn-primary btn-block" disabled={busy||label.trim().length<2} onClick={issue}><Plus size={17}/> Qurilma kodini yaratish</button>{generated&&<div className="token-box"><b>Bir marta ko‘rsatiladigan terminal kodi</b><code>{generated.token}</code><p>Ushbu kodni faqat Note 10 terminalidagi birinchi oynaga kiriting. Xavfsiz joyda saqlang.</p><button className="btn btn-outline btn-block" onClick={async()=>{try{await navigator.clipboard.writeText(generated.token);setCopied(true);}catch{setCopied(false);}}}><Copy size={16}/>{copied?'Nusxalandi':'Kodni nusxalash'}</button></div>}</div><div className="side-panel"><div className="card-title"><ShieldCheck size={21}/><h3>Ulangan qurilmalar</h3></div>{!data.devices.length?<p className="muted">Hali birorta terminal ulanmagan.</p>:data.devices.map(d=><div className="device-row" key={d.id}><div><b>{d.label}</b><p className="muted">{d.last_seen?'Oxirgi aloqa: '+new Date(d.last_seen).toLocaleString('uz-UZ',{timeZone:'Asia/Tashkent'}):'Hali ishlatilmagan'}</p></div><button className={'btn '+(d.active?'btn-danger-light':'btn-outline')} disabled={busy} onClick={()=>{if(confirm(d.active?'Qurilma kodini bloklaysizmi?':'Qurilmani faollashtirasizmi?'))act('editDevice',{id:d.id,active:!d.active});}}><Power size={15}/>{d.active?'Bloklash':'Faollashtirish'}</button></div>)}</div><div className="side-panel"><h3>Note 10’da o‘rnatish</h3><p className="muted">1. Chrome orqali terminal sahifasini oching. 2. Bir martalik kodni kiriting. 3. Brauzer menyusidan “Add to Home screen” ni tanlang. 4. Android’da ekran mahkamlash funksiyasidan foydalaning.</p><a className="btn btn-outline btn-block" href="/terminal" target="_blank" rel="noreferrer"><Smartphone size={17}/> Terminalni ochish</a></div></div></section>;
}
